version: '3.12.3'

services:
  web:
    build: .
    ports:
      - "8000:80"
    volumes:
      - .:/workspace
    environment:
      - PYTHONUNBUFFERED=1
    command: uvicorn app.main:app --host 0.0.0.0 --port 80 --reload

  test:
    build: .
    volumes:
      - .:/workspace
    command: pytest
