"""cascade delete project by founder

Revision ID: bea0ac852d47
Revises: e0d1a9fec412
Create Date: 2024-08-14 21:51:20.754768

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bea0ac852d47'
down_revision: Union[str, None] = 'e0d1a9fec412'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
