name: Create Branch from Issue

on:
  issues:
    types: [opened]

jobs:
  create_branch:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Extract branch name
      id: extract_branch
      run: |
        title="${{ github.event.issue.title }}"
        issue_number="${{ github.event.issue.number }}"
        
        # Determine the prefix (req or fix)
        if [[ "$title" =~ ^REQ: ]]; then
          prefix="req"
        elif [[ "$title" =~ ^FIX: ]]; then
          prefix="fix"
        else
          prefix="issue"
        fi
        
        # Remove the prefix (REQ: or FIX:) and trim whitespace
        clean_title=$(echo "$title" | sed -E 's/^(REQ:|FIX:)\s*//i' | awk '{$1=$1};1')
        
        # Convert to lowercase and replace spaces with hyphens
        branch_name=$(echo "$clean_title" | tr '[:upper:] ' '[:lower:]-')
        
        # Remove any characters that are not alphanumeric, hyphens, or underscores
        branch_name=$(echo "$branch_name" | sed 's/[^a-z0-9-]//g')
        
        # Construct the final branch name
        branch_name="${prefix}/${issue_number}-${branch_name}"
        
        echo "BRANCH_NAME=$branch_name" >> $GITHUB_ENV

    - name: Create branch from develop
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git fetch origin develop
        git checkout -b ${{ env.BRANCH_NAME }} origin/develop
        git push origin ${{ env.BRANCH_NAME }}

    - name: Comment on issue
      uses: actions/github-script@v6
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.name,
            body: `Branch \`${{ env.BRANCH_NAME }}\` has been created for this issue.`
          })